core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls'))
]

home/urls.py
from django.urls import path
from . import views

app_name= 'home'

urlpatterns = [
    
    path("", views.industry_summary_list, name="filter"),
    path("likelihood/", views.likelihood, name="likelihood"),
    path("intensity/", views.intensity, name="intensity"),
    path("relevance/", views.relevance, name="relevance"),

    # path("", views.parse_data, name="parse_data"),
    # path("industry_summary_list/", views.industry_summary_list, name="filter"),
]

home/models.py
from django.db import models
from datetime import datetime
# Create your models here.

class DataIndustry(models.Model):
    end_year = models.CharField(max_length=4, blank=True)
    intensity = models.IntegerField()
    sector = models.CharField(max_length=255)
    topic = models.CharField(max_length=255)
    insight = models.TextField()
    url = models.URLField()
    region = models.CharField(max_length=255, blank=True)
    start_year = models.CharField(max_length=4, blank=True)
    impact = models.CharField(max_length=255, blank=True)
    add_date = models.DateTimeField()
    publish_date = models.DateTimeField()
    country = models.CharField(max_length=255, blank=True)
    relevance = models.IntegerField()
    pestle = models.CharField(max_length=255)
    source = models.CharField(max_length=255)
    title = models.CharField(max_length=255)
    likelihood = models.IntegerField()
    
    class Meta:
        db_table = 'data'
        managed = True
        verbose_name = 'data'
        verbose_name_plural = 'datum'

    def __str__(self) -> str:
        title = self.title
        return title[:50]

    def _get_year(self):
        return str(self.published_date.year)
    
    

    # @classmethod
    # def parse(cls, data):
    #     parsed_data = {}
    #     parsed_data['end_year'] = data.get('end_year', '')
    #     parsed_data['intensity'] = data['intensity']
    #     parsed_data['sector'] = data['sector']
    #     parsed_data['topic'] = data['topic']
    #     parsed_data['insight'] = data['insight']
    #     parsed_data['url'] = data['url']
    #     parsed_data['region'] = data.get('region', '')
    #     parsed_data['start_year'] = data.get('start_year', '')
    #     parsed_data['impact'] = data.get('impact', '')
    #     parsed_data['add_date'] = datetime.strptime(data['added'], '%B, %d %Y %H:%M:%S')
    #     parsed_data['publish_date'] = datetime.strptime(data['published'], '%B, %d %Y %H:%M:%S')
    #     parsed_data['country'] = data.get('country', '')
    #     parsed_data['relevance'] = data['relevance']
    #     parsed_data['pestle'] = data['pestle']
    #     parsed_data['source'] = data['source']
    #     parsed_data['title'] = data['title']
    #     parsed_data['likelihood'] = data['likelihood']
    #     return parsed_data

home/views.py
import json
from django.shortcuts import render
from .models import *
from datetime import datetime
from django.contrib import messages
import django_filters
from django import forms
from django.core.paginator import Paginator
from django.shortcuts import render

# from application.models import *

# Create your views here.

app_name = 'home'

def industry_summary_list(request):
        filter_data = DataIndustryFilter(request.GET, queryset=DataIndustry.objects.all())
        if filter_data:
            paginator = Paginator(filter_data.qs, 25)  
            page_number = request.GET.get("page")
            page_obj = paginator.get_page(page_number)
            return render(request,"filter.html",{"filter": filter_data, "page_obj": page_obj})
        else:
            messages.error(request, 'invalid')
            return redirect('industry_summary_list')



def likelihood(request):
    data = {
        "data": [],
        "lable1": [],
        "lable2": [],
    }
    summaries = DataIndustry.objects.all()[:200]
    for summary in summaries:
        if summary.country or summary.region:
            data["data"].append(summary.likelihood)
            data["lable1"].append(summary.country)
            data["lable2"].append(summary.region)
    context = {
        "data": data,
        "title": "Likelihood",
        "limits": 15,
        "type1": "bar",
        "type2": "line",
    }
    return render(request, 'chart-bar.html', context)
                  


def intensity(request):
    data = {
        "data": [],
        "lable1": [],
        "lable2": [],
    }
    summaries = DataIndustry.objects.all()[:200]
    for summary in summaries:
        if summary.country or summary.region:
            data["data"].append(summary.intensity)
            data["lable1"].append(summary.country)
            data["lable2"].append(summary.region)
    context = {
        "data": data,
        "title": "Intensity",
        "limits": 100,
        "type1": "bar",
        "type2": "line",
    }
    return render( request,"chart-bar.html",context )


def relevance(request):
    data = {
        "data": [],
        "lable1": [],
        "lable2": [],
    }
    summaries = DataIndustry.objects.all()[:200]
    for summary in summaries:
        if summary.country or summary.region:
            data["data"].append(summary.relevance)
            data["lable1"].append(summary.country)
            data["lable2"].append(summary.region)
    context = {
        "data": data,
        "title": "Revelance",
        "limits": 15,
        "type1": "bar",
        "type2": "line",
    }
    return render( request, "chart-bar.html",context)


class DataIndustryFilter(django_filters.FilterSet):
    end_year = django_filters.DateFilter(
        field_name="end_year",
        lookup_expr="lte",
        widget=forms.DateInput(attrs={"class": "form-control"}),
    )
    topic = django_filters.CharFilter(
        lookup_expr="icontains",
        widget=forms.TextInput(attrs={"class": "form-control"}),
    )
    sector = django_filters.CharFilter(
        lookup_expr="icontains",
        widget=forms.TextInput(attrs={"class": "form-control"}),
    )
    region = django_filters.CharFilter(
        lookup_expr="icontains",
        widget=forms.TextInput(attrs={"class": "form-control"}),
    )
    pestle = django_filters.CharFilter(
        lookup_expr="icontains",
        widget=forms.TextInput(attrs={"class": "form-control"}),
    )
    source = django_filters.CharFilter(
        lookup_expr="icontains",
        widget=forms.TextInput(attrs={"class": "form-control"}),
    )

    country = django_filters.CharFilter(
        lookup_expr="icontains",
        widget=forms.TextInput(attrs={"class": "form-control"}),
    )

    class Meta:
        model = DataIndustry
        fields = [ "end_year", "topic", "sector", "region", "pestle", "source", "country",
]


# def parse_data(request):
#     with open('jsondata.json', encoding='utf-8') as f:
#         data = json.load(f)
#         for item in data:
#             try:
#                 parsed_data = DataIndustry.parse(item)
#                 obj, created = DataIndustry.objects.get_or_create(**parsed_data)
#                 if not created:
#                     # The object already existed, do something here if needed
#                     pass
#             except ValueError as e:
#                 # Handle the error and log it or display an appropriate message
#                 print(f"Error parsing data: {e}")
#     return render(request, 'parse_data.html')

home/templates/base.html
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Dashboard - SB Admin</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/simple-datatables@latest/dist/style.css" rel="stylesheet"/>
    <link href="{% static 'css/styles.css' %}" rel="stylesheet">
    <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
  </head>
  <body class="sb-nav-fixed">
    {% include 'nav.html' %}
    <div id="layoutSidenav">
      {% include 'side-nav.html' %}
      <div id="layoutSidenav_content">
        {% block content %}{% endblock %}
      </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="{% static 'js/scripts.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js"
            crossorigin="anonymous"></script>
    <script src="{% static 'assets/demo/chart-area-demo.js' %}"></script>
    <script src="{% static 'assets/demo/chart-bar-demo.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/simple-datatables@latest"
            crossorigin="anonymous"></script>
    <script src="{% static 'js/datatables-simple-demo.js' %}"></script>
    {% block script %}
    {% endblock script %}
  </body>
</html>

home/templates/chart-bar.html
{% extends 'base.html' %}
{% block content %}
  <main>
    <div class="container-fluid px-4">
      <h2 class="mt-4">Countrys' Chart for - {{ title }}  </h2>
      <button id="toggle-chart" class="btn bg-info m-2">Toggle Chart Type</button>
      <div class="row">
        <div class="col-12">
          <div class="card mb-4">
            <div class="card-body">
              <canvas id="myChart"></canvas>
            </div>
          </div>
        </div>
      </div>
    </div>
  </main>

  {% endblock content %}
{% block script %}

<script>
  var ctx = document.getElementById("myChart");
  var chartType = 'bar';
  var myChart = new Chart(ctx, {
    type: chartType,
    data: {
      labels: {{ data.lable1|safe}},
      datasets: [{
        lineTension: 0.3,
        backgroundColor: "rgba(2,117,216,0.2)",
        borderColor: "rgba(2,117,216,1)",
        pointRadius: 5,
        pointBackgroundColor: "rgba(2,117,216,1)",
        pointBorderColor: "rgba(255,255,255,0.8)",
        pointHoverRadius: 5,
        pointHoverBackgroundColor: "rgba(2,117,216,1)",
        pointHitRadius: 50,
        pointBorderWidth: 2,
        data: {{data.data|safe}},
      }],
    },
    options: {
      scales: {
        xAxes: [{
          gridLines: {
            display: false,
          },
          ticks: {
            min: 0,
            max:1000,
            maxTicksLimit:20
          }
        }],
        yAxes: [{
          ticks: {
            min: 0,
            max: {{limits|safe}},
            maxTicksLimit: 15
          },
          gridLines: {
            color: "rgba(0, 0, 0, .125)",
          }
        }],
      },
      legend: {
        display:false,
      }
    }
  });

  var toggleButton = document.getElementById("toggle-chart");
  toggleButton.addEventListener("click", function() {
    if (chartType === 'bar') {
      chartType = 'line';
    } else {
      chartType = 'bar';
    }
    myChart.destroy();
    myChart = new Chart(ctx, {
      type: chartType,
      data: {
        labels: {{ data.lable1|safe}},
        datasets: [{
          lineTension: 0.3,
          backgroundColor: "rgba(2,117,216,0.2)",
          borderColor: "rgba(2,117,216,1)",
          pointRadius: 5,
          pointBackgroundColor: "rgba(2,117,216,1)",
          pointBorderColor: "rgba(255,255,255,0.8)",
          pointHoverRadius: 5,
          pointHoverBackgroundColor: "rgba(2,117,216,1)",
          pointHitRadius: 50,
          pointBorderWidth: 2,
          data: {{data.data|safe}},
        }],
      },
      options: {
        scales: {
          xAxes: [{
            gridLines: {
              display: false,
            },
            ticks: {
              min: 0,
              max:1000,
              maxTicksLimit:20
            }
          }],
          yAxes: [{
            ticks: {
              min: 0,
              max: {{limits|safe}},
              maxTicksLimit: 15
            },
            gridLines: {
              color: "rgba(0, 0, 0, .125)",
            }
          }],
        },
        legend: {
          display:false,
        }
      }
    });
  });
</script>

{% endblock %}

home/templates/filter.html
{% extends 'base.html' %}
{% load humanize %}

{% block content %}
  <main>
    <div class="container-fluid px-4 bg-secondary">
      
      <div class="row">
        <div class="col-12">
          <div class="card mb-4">
            <div class="card-header bg-dark text-light">Dashboard Filter</div>
          </div>
        </div>
        <div class="col-12">
          <div class="card mb-4">

            <div class="card-header bg-secondary">
              <form method="GET">


                <div class="row">
                  <div class="col-md-4">
                    <p>
                      <input type="date" name="end_year" class="form-control" id="id_end_year" placeholder="End year is less than or equal to">
                    </p>
                  </div>
                  <div class="col-md-4">
                    <p>
                      <input type="text" name="topic" class="form-control" id="id_topic" placeholder="Topic contains">
                    </p>
                  </div>
                  <div class="col-md-4">
                    <p>
                      <input type="text" name="sector" class="form-control" id="id_sector" placeholder="Sector contains">
                    </p>
                  </div>
                </div>
                <div class="row">
                  <div class="col-md-4">
                    <p>
                      <input type="text" name="region" class="form-control" id="id_region" placeholder="Region ">
                    </p>
                  </div>
                  <div class="col-md-4">
                    <p>
                      <input type="text" name="pestle" class="form-control" id="id_pestle" placeholder="Pestle ">
                    </p>
                  </div>
                  <div class="col-md-4">
                    <p>
                      <input type="text" name="source" class="form-control" id="id_source" placeholder="Sources ">
                    </p>
                  </div>
                </div>
                <div class="row my-auto">
                  <div class="col-md-4">
                    <p>
                      <input type="text" name="country" class="form-control" id="id_country" placeholder="Country ">
                    </p>
                  </div>

                </div>
                <button class="btn btn-primary mb-3  col-lg-6" type="submit">Filter</button> <br>

                <a class="btn btn-danger  col-lg-6"
                   href="?{% for key in request.GET %}{% if key != 'page' %}&{{ key }}={% endif %}{% endfor %}"
                   class="btn btn-secondary">Clear Filter
                </a>

              </form>
            </div>

            <div class="card-body table-responsive">
              <table class="table table-dark table-hover table-bordered">
                <thead>
                  <tr>
                    <th class="text-black" colspan="16">Total Result Found-{{ filter.qs.count }}</th>
                  </tr>
                  <tr>
                    <th>SR. No.</th>
                    <th>Topic</th>
                    <th>Region</th>
                    <th>Sector</th>
                    <th>Country</th>
                    <th>PESTLE</th>
                    <th>Sources</th>
                    <th>Impact</th>
                    <th>Insight</th>
                    <th>Title</th>
                    <th>Likelihood</th>
                    <th>Relevance</th>
                    <th>Intensity</th>
                    <th>Start Year</th>
                    <th>End Year</th>
                    <th>Add Date</th>
                    <th>Publish Date</th>
                  </tr>
                </thead>
                <tbody>
                  {% for summary in page_obj %}
                    <tr>
                      <td>{{ forloop.counter }}</td>
                      <td>{{ summary.topic }}</td>
                      <td>{{ summary.region }}</td>
                      <td>{{ summary.sector }}</td>
                      <td>
                        {{ summary.country }}
                      </td>
                      <td>
                        {{ summary.pestle }}
                      </td>
                      <td>
                        {{ summary.source }}
                      </td>
                      <td>
                        {{ summary.impact }}
                      </td>
                      <td>
                        {{ summary.insight|slice:":20"  }}
                      </td>
                      <td>
                        {{ summary.title|slice:":20"  }}.....
                      </td>
                      <td>
                        {{ summary.likelihood }}
                      </td>
                      <td>
                        {{ summary.relevance }}
                      </td>
                      <td>
                        {{ summary.intensity }}
                      </td>
                      <td>
                        {{ summary.start_year|naturalday }}
                      </td>
                      <td>
                        {{ summary.end_year|naturalday }}
                      </td>
                      <td>
                        {{ summary.add_date|naturalday }}
                      </td>
                      <td>
                        {{ summary.publish_date|naturalday }}
                      </td>
                    </tr>
                  {% endfor %}
                </tbody>
                <tfoot>
                  <tr>
                    <td colspan="8">
                      <div class="pagination">
                        <span class="step-links">
                          {% if page_obj.has_previous %}
                            <a class="btn btn-danger" href="?page=1">&laquo; first</a>
                            <a class="btn btn-danger"
                               href="?page={{ page_obj.previous_page_number }}">previous</a>
                          {% endif %}
                          <span class="current">
                            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                          </span>
                          {% if page_obj.has_next %}
                            <a class="btn btn-danger" href="?page={{ page_obj.next_page_number }}">next</a>
                            <a class="btn btn-danger"
                               href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                          {% endif %}
                        </span>
                      </td>
                    </tr>
                  </tfoot>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </main>
  {% endblock %}

home/templates/nav.html
<nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
  <!-- Navbar Brand -->
  <a class="navbar-brand ps-3" href="index.html">Dashboard</a>
  <!-- Sidebar Toggle -->
  <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0"
          id="sidebarToggle"
          href="#!">
    <i class="fas fa-bars"></i>
  </button>

</nav>

home/templates/side-nav.html
<div id="layoutSidenav_nav">
  <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
    <div class="sb-sidenav-menu">
      <div class="nav">
        <div class="collapse"
             id="collapseLayouts"
             aria-labelledby="headingOne"
             data-bs-parent="#sidenavAccordion">
          <nav class="sb-sidenav-menu-nested nav">
            <a class="nav-link" href="layout-static.html">Static Navigation</a>
            <a class="nav-link" href="layout-sidenav-light.html">Light Sidenav</a>
          </nav>
        </div>
        <nav class="sb-sidenav-menu-nested nav">
          <a class="nav-link" href="{% url 'home:filter' %}">All Filters</a>
          <a class="nav-link" href="{% url 'home:likelihood' %}">Visualizer-One</a>
          <a class="nav-link" href="{% url 'home:relevance' %}">Visualizer-Two</a>
          <a class="nav-link" href="{% url 'home:intensity' %}">Visualizer-Three</a>
        </nav>
      </div>
    </nav>
  </div>